name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: doepocregistry # Set this to your ACR name
  CONTAINER_APP_NAME: doepoccontainerapp # Set this to your Container Instance name
  RESOURCE_GROUP: rg-doepoc # Set this to your resource group
  IMAGE_NAME: windows-server-2022-iis # Set this to your desired image name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        uses: azure/CLI@v1
        with:
          inlineScript: |
           az container delete 
           --resource-group ${{ env.RESOURCE_GROUP }} 
           --name ${{ env.CONTAINER_APP_NAME }} 
           --yes

      
           az container create 
           --resource-group ${{ env.RESOURCE_GROUP }} 
           --name ${{ env.CONTAINER_APP_NAME }} 
           --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} 
           --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io 
           --registry-username ${{ secrets.ACR_USERNAME }} 
           --registry-password ${{ secrets.ACR_PASSWORD }} 
           --dns-name-label ${{ env.CONTAINER_APP_NAME }} 
           --ports 80 443 
           --cpu 1 
           --memory 1.5
